Support ncm2
autozimu/LanguageClient-neovim pull request #504
Opened 2018-07-08 04:07 UTC by roxma

https://github.com/ncm2/ncm2

Note that the ctx field in the callback may have extra fields in the future, it could be added either by ncm2 core or by ncm2 plugins. It's better to send the whole copy back instead of sending the strongly typed context, which might lose some data.

```rust
       let orig_ctx: Value = serde_json::from_value(rpc::to_value(params.clone())?)?;
       let orig_ctx = &orig_ctx["ctx"];
```

This PR is tested with rls.

2018-07-08 04:53 UTC, roxma commented
Also tested with [ncm2-snipmate](https://github.com/ncm2/ncm2-snipmate) and [ncm2-ultisnips](https://github.com/ncm2/ncm2-ultisnips)

2018-07-09 00:15 UTC, autozimu requested changes

2018-07-09 00:15 UTC, autozimu commented on src/languageclient.rs
> +        info!("End register NCM source");
Please update the message content.

2018-07-09 00:15 UTC, autozimu commented on src/types.rs
> +pub struct NCM2OnCompleteParams {
I don't think this is ever used.

2018-07-09 18:27 UTC, merged

2018-07-09 18:28 UTC, autozimu commented
Thanks.

2021-03-26 08:22 UTC, run27017 commented
What effects? How about auto completeion?

2021-03-26 08:32 UTC, martskins commented
@run27017 I don't think I understand the question. Care to elaborate?

2021-03-26 08:45 UTC, run27017 commented
@martskins Sorry about it. I am seeking the common integration method of ncm2 and LanguageClient-neovim, which supporting the auto completion. It seems this PR is not related to it, and I will search the data in other place.