Clear previous diagnostics in case if LanguageClient_diagnosticsList is "Location"
autozimu/LanguageClient-neovim pull request #908
Opened 2019-10-30 15:14 UTC by ruslan-savina

If g:LanguageClient_diagnosticsList = 'Location' we have to clear previous diagnostic results.
As a result, we will have diagnostics only for a current buffer in case if 'Location' is set.

Fixes:
#763

2019-10-31 01:17 UTC, autozimu commented
It seems like this would depend on language server's publishing diagnostics sequence. It only works when language server publishes diagnostics for current buffer last.

2019-11-09 21:43 UTC, ruslan-savina commented
I've checked the [specification](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/) and it looks like there is no such thing as diagnostics publishing sequence. All language servers should work identically.

2019-11-27 02:12 UTC, autozimu commented
> All language servers should work identically

There is no guarantee this is true.

A better way would be comparing current buffer filename with the one in diagnostic list.

2019-12-02 04:46 UTC, autozimu requested changes
Please check previous comment

2019-12-02 18:51 UTC, closed without merging