add feature to customize highlight for floating hover window
autozimu/LanguageClient-neovim pull request #966
Opened 2020-01-30 03:01 UTC by 110y

Add `g:LanguageClient_floatingHoverHighlight` to customize highlights for floating hover window.

2020-02-01 01:26 UTC, autozimu commented on autoload/LanguageClient.vim
> -        setlocal winhl=Normal:CursorLine
Nit: GetVar takes a second parameter as default.

2020-02-01 01:32 UTC, autozimu commented on doc/LanguageClient.txt
> +Default: CursorLine
It might be more convenient to allow user specify the winhl themselves, i.e., values can be `Normal:MyNormal,NormalNC:MyNormalNC`

2020-02-01 01:32 UTC, autozimu requested changes
Please check previous comments.

2020-02-01 02:51 UTC, 110y commented
@autozimu 

Thank you for responding!
I've fixed the code based on you review: 311db07
Please take another look!

2020-02-03 04:56 UTC, merged

2020-02-03 04:57 UTC, autozimu commented
Thanks!